#!/usr/bin/env bash
# mysql
# Written by Rich Carpenter
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

curl -o /home/"${BASE_USER}"/Downloads/webmin-setup-repo.sh https://raw.githubusercontent.com/webmin/webmin/master/webmin-setup-repo.sh
sh /home/"${BASE_USER}"/Downloads/webmin-setup-repo.sh -f
apt-get install webmin --install-recommends -y
rm /home/"${BASE_USER}"/Downloads/webmin-setup-repo.sh

unpack /filesystem/ /