#!/usr/bin/env bash
# apache2
# Provides webserver via apache2
# Written by Rich Carpenter
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

apt-get update --allow-releaseinfo-change
apt-get install -y apache2 mariadb-client php php-mysql php-gd php-curl php-mbstring php-mcrypt php-zip libapache2-mod-php
apt autoremove --purge -y

#Backup existing php.ini file
inifile=$(php -i | grep "Loaded Configuration File" | sed 's/.*Loaded Configuration File => //g')

sudo cp $inifile /home/"${BASE_USER}"/Downloads

# Update the php directivies required by ianseo
# upload_max_filesize = 256M
# post_max_size = 256M
# memory_limit = 1024M

sudo sed -i 's,^upload_max_filesize =.*$,upload_max_filesize = 256M,' $inifile
sudo sed -i 's,^post_max_size =.*$,post_max_size = 256M,' $inifile
sudo sed -i 's,^memory_limit =.*$,memory_limit = 1024M,' $inifile
sudo sed -i 's,^max_execution_time =.*$,max_execution_time = 120,' $inifile

# add ianseo apahe2 config file
unpack /filesystem /
sudo a2ensite ianseo