#!/usr/bin/env bash
# apache2
# Provides webserver via apache2
# Written by Rich Carpenter
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

apt-get update --allow-releaseinfo-change
apt-get install -y apache2 mariadb-client php php-mysql php-gd php-curl php-mbstring php-mcrypt php-zip libapache2-mod-php
apt autoremove --purge -y

#Backup existing php.ini file
inifile=$(php -i | grep "Loaded Configuration File" | sed 's/.*Loaded Configuration File => //g')

cp $inifile ~/phpini.bak

# Update the php directivies required by ianseo
# upload_max_filesize = 256M
# post_max_size = 256M
# memory_limit = 1024M

sed -i 's,^upload_max_filesize =.*$,upload_max_filesize = '"$APACHE2_UPLOAD_MAX_FILESIZE"',' $inifile
sed -i 's,^post_max_size =.*$,post_max_size = '"$APACHE2_POST_MAX_SIZE"',' $inifile
sed -i 's,^memory_limit =.*$,memory_limit = '"$APACHE2_MEMORY_LIMIT"',' $inifile
sed -i 's,^max_execution_time =.*$,max_execution_time = '"$APACHE2_MAX_EXECUTION_TIME"',' $inifile

# add ianseo apahe2 config file
unpack /filesystem /
a2ensite ianseo
