#!/usr/bin/env bash
# ianseopi base module
# Written by Rich Carpenter
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap


#unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
#unpack /filesystem/home/root /root root
#unpack /filesystem/boot /boot

#echo "This is an example module, install and set up what you need here!"
#echo "$EXAMPLE_VAR"

# Unpack root at the end, so files are modified before
#unpack /filesystem/root /

# 