name: Build Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install gawk util-linux coreutils qemu-user-static p7zip-full git python3-git
      - name: Checkout CustomPiOS
        uses: actions/checkout@v6.0.1
        with:
          repository: "guysoft/CustomPiOS"
          path: CustomPiOS
          # Pin to specific commit on devel, tip: use Mend Renovate to auto-update this using Pull-Requests! 
          # This way your chances of dealing with a broken build are minimalized.
          ref: "79b77a4c1a34ef551ab09e9bd84710d048b65e55"
      - name: Checkout Project Repository
        uses: actions/checkout@v6.0.1
        with:
          path: repository
          submodules: true
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.5.0
        with:
          versionSpec: "6.7.x"
      - name: Use GitVersion
        uses: gittools/actions/gitversion/execute@v4.5.0
        id: gitversion
        with:
          targetPath: repository
      - name: Download Base Image (default)
        run: |
          cd repository/src/image
          wget -c --trust-server-names 'https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2026-04-21/2026-04-21-raspios-trixie-arm64-lite.img.xz'
      - name: Update CustomPiOS Paths
        run: |
          cd repository/src
          ../../CustomPiOS/src/update-custompios-paths
      - name: Set release image version
        run: |
          source repository/src/config
          echo "DIST_VERSION=${{ steps.gitversion.outputs.majorMinorPatch }}" > repository/src/config.local
      - name: Build Image
        run: |
          sudo modprobe loop
          cd repository/src
          sudo bash -x ./build_dist
