name: Build Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install gawk util-linux coreutils qemu-user-static p7zip-full git
      - name: Checkout CustomPiOS
        uses: actions/checkout@v6.0.1
        with:
          repository: "guysoft/CustomPiOS"
          path: CustomPiOS
          # Pin to specific commit on devel, tip: use Mend Renovate to auto-update this using Pull-Requests! 
          # This way your chances of dealing with a broken build are minimalized.
          ref: "79b77a4c1a34ef551ab09e9bd84710d048b65e55"
      - name: Checkout Project Repository
        uses: actions/checkout@v6.0.1
        with:
          path: repository
          submodules: true
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.5.0
        with:
          versionSpec: "6.7.x"
      - name: Use GitVersion
        uses: gittools/actions/gitversion/execute@v4.5.0
        id: gitversion
        with:
          targetPath: repository
      - run: |
          echo "FullSemVer (env.fullSemVer)            : ${{ env.fullSemVer }}"
          name: Display GitVersion variables (without prefix)
